DROP FUNCTION IF EXISTS slugfy;

DELIMITER $$

 CREATE DEFINER=CURRENT_USER FUNCTION slugfy(Texto VARCHAR(150))
 RETURNS VARCHAR(150)
 NOT DETERMINISTIC
 BEGIN
 DECLARE RTD VARCHAR(150);
 SET RTD   = UPPER(TRIM(Texto));
 SET RTD = REPLACE(RTD,'\'','');
 SET RTD = REPLACE(RTD,'`','');
 SET RTD = REPLACE(RTD,'.','');
 SET RTD = REPLACE(RTD,'-','');
 SET RTD = REPLACE(RTD,'&','-');
 SET RTD = REPLACE(RTD,' ','-');
 SET RTD = REPLACE(RTD,'´','');
 SET RTD = REPLACE(RTD,'À','A');
 SET RTD = REPLACE(RTD,'Á','A');
 SET RTD = REPLACE(RTD,'Â','A');
 SET RTD = REPLACE(RTD,'Ã','A');
 SET RTD = REPLACE(RTD,'Ä','A');
 SET RTD = REPLACE(RTD,'Å','A');
 SET RTD = REPLACE(RTD,'È','E');
 SET RTD = REPLACE(RTD,'É','E');
 SET RTD = REPLACE(RTD,'Ê','E');
 SET RTD = REPLACE(RTD,'Ë','E');
 SET RTD = REPLACE(RTD,'Ì','I');
 SET RTD = REPLACE(RTD,'Í','I');
 SET RTD = REPLACE(RTD,'Î','I');
 SET RTD = REPLACE(RTD,'Ï','I');
 SET RTD = REPLACE(RTD,'Ò','O');
 SET RTD = REPLACE(RTD,'Ó','O');
 SET RTD = REPLACE(RTD,'Ô','O');
 SET RTD = REPLACE(RTD,'Õ','O');
 SET RTD = REPLACE(RTD,'Ö','O');
 SET RTD = REPLACE(RTD,'Ù','U');
 SET RTD = REPLACE(RTD,'Ú','U');
 SET RTD = REPLACE(RTD,'Û','U');
 SET RTD = REPLACE(RTD,'Ü','U');
 SET RTD = REPLACE(RTD,'Ø','O');
 SET RTD = REPLACE(RTD,'Æ','A');
 SET RTD = REPLACE(RTD,'Ð','D');
 SET RTD = REPLACE(RTD,'Ñ','N');
 SET RTD = REPLACE(RTD,'Ý','Y');
 SET RTD = REPLACE(RTD,'Þ','B');
 SET RTD = REPLACE(RTD,'ß','S');
 SET RTD = REPLACE(RTD,'Ç','C');
 SET RTD = REPLACE(RTD,'--','-');

 RETURN LOWER(RTD);

END$$

DELIMITER ;
